version: '3.3'
services:
  wintersmith-docker:
    build:
      context: ../
      dockerfile: blogs-deploy/wintersmith-docker.Dockerfile
    image: "${REPOSITORY_URI_WINTERSMITH_DOCKER}:latest"
    env_file: prod.env
  blogs-hackbytes:
    build:
      context: ../
      dockerfile: blogs-deploy/hackbytes.io.Dockerfile
    image: "${REPOSITORY_URI_BLOGS_HACKBYTES}:latest"
    ports:
      - '8082:8080'
    volumes:
      - type: bind
        source: ../blogs-libs
        target: /home/wintersmith/blogs-libs
      - type: bind
        source: ../blogs-universal/src
        target: /home/wintersmith/blogs-universal/src
      - type: bind
        source: ../blogs-hackbytes
        target: /home/wintersmith/blogs-hackbytes
    env_file: prod.env
    depends_on:
      - wintersmith-docker
  blogs-nitelite:
    build:
      context: ../
      dockerfile: blogs-deploy/nitelite.io.Dockerfile
    image: "${REPOSITORY_URI_BLOGS_NITELITE}:latest"
    ports:
      - '8084:8080'
    volumes:
      - type: bind
        source: ../blogs-libs
        target: /home/wintersmith/blogs-libs
      - type: bind
        source: ../blogs-universal/src
        target: /home/wintersmith/blogs-universal/src
      - type: bind
        source: ../blogs-nitelite
        target: /home/wintersmith/blogs-nitelite
    env_file: prod.env
    depends_on:
      - wintersmith-docker
